### ISSUE TITLE
switch from the pull_request event to the status event

### ISSUE THREAD

**Issue by travi** [greenkeeper-keeper/hapi-greenkeeper-keeper#21]
https://developer.github.com/v3/activity/events/types/#statusevent over https://developer.github.com/v3/activity/events/types/#pullrequestevent (current)

as mentioned in https://github.com/kkemple/greenkeeper-keeper/issues/27, it is probably more appropriate to drive greenkeeper-keeper's processing based on the statuses changing to `success` rather than only being based on a PR being opened.

this would enable us to remove the waiting during processing when some checks are still pending and also handle status updates that happen after the timeout and after a redeploy of the instance that was waiting for status updates on outstanding PRs.

**Comment by nkbt** [comment]
Sounds great!

**Comment by travi** [comment]
i'm still thinking about this one. the part that i haven't had a chance to confirm yet is if this can be a complete switch or if both events would be needed. 

either way, i think the status event is a replacement for the polling when the overall commit status is `pending`. however, i'm worried that there may be cases where the `status` event might not fire after the `pull_request` event.

greenkeeper waits to hear back about the status of a branch before it opens the PR. because of this, there are likely some scenarios where all of the status checks have already completed before the PR is opened. travis has an additional check that executes after the PR is opened, but there are plenty of other checks that do not.
