### ISSUE TITLE
resolve security issues

### ISSUE THREAD

**Issue by travi** [greenkeeper-keeper/hapi-greenkeeper-keeper#382]
the node security project found [vulnerabilities](https://nodesecurity.io/orgs/greenkeeper-keeper/projects/e50e1890-ce5d-4e0e-a8c6-ad952e29a369) in dependencies of [`highwire`](https://github.com/kkemple/highwire), which was used as the request library in the original implementation of this library. Since `highwire` hasn't seen much maintenance lately, it's probably better to just move to a more popular request library.

**Comment by travi** [comment]
im not sure how popular [r2](https://github.com/mikeal/r2) truly is yet, but it seems like a logical replacement if we stick with a simple request library. however, this is also a good chance to consider a switch to an actual github sdk, like [`@octokit/rest`](https://github.com/octokit/node-github) (previously `github`).

**Comment by travi** [comment]
this project makes heavy use of the hypermedia provided in the github api responses to follow links to related resources rather than manually building direct requests from resource metadata. the last time i looked very deep at the octokit sdk, it was more focused on building direct requests rather than following links, so i'm not sure it would be a good fit if that is still true.

@gr2m is this still the octokit focus, or would it also support following links (starting from status webhooks)? any suggested reading that would help me decide if i should migrate in that direction?

**Comment by gr2m** [comment]
Note that `r2` has a lot of stars just because Mikeal created `request` :D I don’t think lots of people are actually using it in production. I tried and I run into several problems, not with `r2` itself (it’s quite tiny) but with [node-fetch](https://github.com/bitinn/node-fetch).

I’d love you to use the new `@octokit/rest` once it’s released, most likely next week. If you run into any problem with it, you can ping me and I’ll help to resolve it. 

The hypermedia links is just an internal implementation detail of `@octokit/rest`, if you use the methods like `github.repos.get()` etc you won’t be affected by it. It’s actually pretty tiny, too. In future we will expose a generict `github.request()` method in which you can pass URL templates like so 

```js
github.request({
  method: 'get',
  url: '/orgs/:org/repos',
  org: 'greenkeeper-keeper',
  type: 'public',
  per_page: 10,
  page: 2
})
```

And it will send the according http request for you. The method already exist in `@octokit/rest` but it’s not considered public API yet.

Let me know if you have any further questions.

**Comment by travi** [comment]
> Note that r2 has a lot of stars just because Mikeal created request :D I don’t think lots of people are actually using it in production.

yeah, that was kind of my expectation, but i havent looked very deep yet. its gotten enough attention that i've at least seen it mentioned lately.

mainly, i'm just looking for something with a promise based api (if i dont end up going with `@octokit/rest`). one other piece with `node-fetch` that crossed my mind is that i'd have to rethink my high-level tests since i imagine `node-fetch` probably isnt supported by `nock` at this point.

my use of hyperlinks is intended to be a bit more first class, which is part of my concern with what i've previously seen of octokit. however, in looking back at this code to provide a more concrete example of my following of links, it looks like i [gave up on trying to directly follow links](https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper/blob/master/src/github/actions.js) to make the necessary calls. i remember there being shortcomings to the links provided in the github responses, but i incorrectly remembered being more successful than i guess i actually was :\

if octokit provided methods that allow me to follow the links intentionally, that would have been awesome, but i'm now realizing that it would have to fill in some major gaps in github's approach to hypermedia. probably why i previously noticed the ability to follow links was mostly missing from previous octokit versions. i guess its been a while since ive been very deep into working directly with the github api.

so maybe octokit is a closer match to what i need than i was thinking. what is the underlying request library for octokit then, after the changes youve been working on (would i still be able to leverage `nock`)? i may not get to it right away, but i'm thinking its worth a shot.

**Comment by gr2m** [comment]
> node-fetch probably isnt supported by nock at this point

that should make no difference. nock is hooking into Node’s low-level http bindings, `nock` should work with any request library in node

> what is the underlying request library for octokit

It currently uses the core modules `http` / `https` directly:
https://github.com/octokit/node-github/blob/677/rename-to-octokit-rest-clean/lib/request/request.js

> my use of hyperlinks is intended to be a bit more first class

I’d be interested to learn more about this, and discuss how the new `@octokit/rest` can help!  Following hypermedia links should definitely be simple, and there are now also (experimental) APIs for plugins and for hooks into request lifecycle, see https://github.com/octokit/node-github/tree/677/rename-to-octokit-rest-clean/lib/plugins

**Comment by travi** [comment]
> nock is hooking into Node’s low-level http bindings, `nock` should work with any request library in node

ah, nice. i didn't realize that, but good to know. i always assumed it was just stubbing `request` since so many of the tools out there assume you are using that.

> I’d be interested to learn more about this, and discuss how the new @octokit/rest can help! Following hypermedia links should definitely be simple, 

unfortunately, i doubt there is much that octokit can do now that i'm remembering more detail about the reality of the github api responses. hyperlinks are provided for some of the major functionality, but does not include links for everything. it appears that, even with all the digging that i did at the time, the links that would have enabled the calls needed by `greenkeeper-keeper` simply weren't provided in the responses :(

as a side note, i'm a big fan of the [HAL spec](http://stateless.co/hal_specification.html), which is how i build my rest apis. it is very focused on hypermedia for both relationships and defining available actions. i like to use [traverson](https://github.com/traverson) in my clients because it pretty much [has first-class support for hal](https://github.com/traverson/traverson-hal) (there are other adapters for other approaches to hypermedia) and makes traversal of a series of links very simple. that is always my preferred approach, but obviously depends very much on the api provider's use of hypermedia. 

in the absence of links, though, no library on top of the raw requests can easily make up for that. instead, we're left to manually build the urls for most of the requests.

**Comment by gr2m** [comment]
okay, got it.

But still if there are certain flows that require multiple API calls and you are not sure how to approach it, I’d be happy to help.

GitHub itself goes all in on GraphQL. It will probably take another year but moving forward that will be the recommended way to interact with GitHub :)

**Comment by travi** [comment]
- [ ] [merge](https://octokit.github.io/rest.js/#api-PullRequests-merge) for https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper/blob/334613df09c3d9d048213d2ff4d457b9922bac51/src/github/actions.js#L56
  * instead of the full base url, would need separate `owner`, `repo`, `number`
- [ ] delete branch for https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper/blob/334613df09c3d9d048213d2ff4d457b9922bac51/src/github/actions.js#L69
  * doesnt appear to be directly available in octokit
- [ ] get PRs from commit for https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper/blob/334613df09c3d9d048213d2ff4d457b9922bac51/src/github/actions.js#L81
  * doesnt seem to exist directly in octokit
- [ ] [add comment](https://octokit.github.io/rest.js/#api-PullRequests-createComment) for https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper/blob/334613df09c3d9d048213d2ff4d457b9922bac51/src/github/actions.js#L76
  * instead of full url, need separate `owner`, `repo`, `number`
- [ ] [get commit statuses](https://octokit.github.io/rest.js/#api-Repos-getStatuses) for https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper/blob/334613df09c3d9d048213d2ff4d457b9922bac51/src/github/actions.js#L22
  * instead of full repo name, need separate `owner`, `repo`

**Comment by travi** [comment]
[status event payload](https://developer.github.com/v3/activity/events/types/#statusevent)

**Comment by travi** [comment]
@gr2m i'm having trouble finding octokit methods for deleting a branch or for finding PRs from a commit. do these exist and i'm just overlooking them?

**Comment by gr2m** [comment]
> deleting a branch

```js
octokit.gitdata.deleteReference({owner, repo, ref: `heads/${branchName}`})
```

see

- https://developer.github.com/v3/git/refs/#delete-a-reference
- https://octokit.github.io/rest.js/#api-Gitdata-deleteReference

> finding PRs from a commit

There is no direct REST API or it, but you can use the search API:

```js
octokit.search.issues({q: commit.sha})
```

**Comment by travi** [comment]
thanks!

> There is no direct REST API or it, but you can use the search API:
>
> > octokit.search.issues({q: commit.sha})

would the results of that search be limited to PRs though? since a `status` event is tied to a commit, rather than a PR or branch, the goal is to find the associated PR, so that it can be accepted:

https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper/blob/334613df09c3d9d048213d2ff4d457b9922bac51/src/handler.js#L42-L47

**Comment by gr2m** [comment]
yes, `octokit.search.issues()` only returns issues, see https://developer.github.com/v3/search/#search-issues

the `release-notifier` app is using that API to find pull requests based on commits in order to notify contirbutors from PRs that their changes have been released
