### ISSUE TITLE
idea: automatically configure webhooks for all users projects

### ISSUE THREAD

**Issue by cdaringe** [greenkeeper-keeper/hapi-greenkeeper-keeper#471]
# problem

- manually creating webhooks can be a pain, slow, and error prone

# discussion

- the github api lets us [create webhooks](https://developer.github.com/v3/repos/hooks/).
- provided the URI for the GKK server (e.g. `GKK_URL=gkk.myhost.com`),
  - pre-autoconfiguring, we could self test that our GKK instance is accessible/well configured (i'm thinking something like `GET /payload?self_test=1`)
  - on success of self-test, iterate over the users repos, and create hooks!

what do folks think?

**Comment by travi** [comment]
would certainly be helpful. mostly an issue of finding time to get it working. i'm very open to contributions around this.

related: https://github.com/greenkeeper-keeper/meta/issues/9

**Comment by cdaringe** [comment]
greenkeeper-keeper/meta#9 is close enough. closing this issue to consolidate any conversation over there.  apologies for missing that
